# Generated by Django 5.2.9 on 2025-12-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_category_options_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[(0, "Draft"), (1, "Published")], default="Draft", max_length=20
            ),
        ),
    ]
