# Generated by Django 5.2.9 on 2025-12-22 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_contact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
